### ISSUE TITLE
Creating new scene references thru script?

### ISSUE THREAD

**Issue by MikkoKyl1** [JohannesMP/unity-scene-reference#6]
Due to my code, I need to create new SceneReferences through a script (primarily turning GameObject.scene. into a SceneReference). I know it's possible to create new ones, but I haven't really found a good way to actually insert the values (build index, file path etc.) into it. Is this even possible, or have I just missed it?

EDIT: Solved the issue thanks to the ScenePath variable being public.
EDIT 2: Re-opened issue, as trying to assign a file path through a script only kept throwing NullReferenceExceptions. Problem still persists.

**Comment by starikcetin** [comment]
Are we talking about runtime or editor scripts?

**Comment by MikkoKyl1** [comment]
> Are we talking about runtime or editor scripts?

At runtime. Say, press a button in-game and try to assign the scene the button is in into a SceneReference object.

**Comment by starikcetin** [comment]
This plugin is for helping the serialization of scenes in the editor so that we don't have to hardcode scene paths, it doesn't do much in runtime besides giving you the scene path it serialized in the editor.

In runtime you must already have some way of identifying the scene already, so you can just use that directly. For example, `GameObject.scene` is giving you the scene identifier, so you can use that directly.

Maybe I am misunderstanding your use case here. Why do you want to do this exactly? Can you elaborate a little bit?

**Comment by MikkoKyl1** [comment]
> This plugin is for helping the serialization of scenes in the editor so that we don't have to hardcode scene paths, it doesn't do much in runtime besides giving you the scene path it serialized in the editor.
> 
> In runtime you must already have some way of identifying the scene already, so you can just use that directly. For example, `GameObject.scene` is giving you the scene identifier, so you can use that directly.
> 
> Maybe I am misunderstanding your use case here. Why do you want to do this exactly? Can you elaborate a little bit?

It probably is unnecessary, now that I think about it. I wanted all my scene handling to use the single variable type, so I wanted to somehow shoehorn them in places that didn't need them, but that's just my fault. Even if I can't/don't need to do it, this has still helped me quite a bit.

Thank you for this, and sorry to be a bother!

**Comment by starikcetin** [comment]
> It probably is unnecessary, now that I think about it. I wanted all my scene handling to use the single variable type, so I wanted to somehow shoehorn them in places that didn't need them, but that's just my fault. Even if I can't/don't need to do it, this has still helped me quite a bit.
> 
> Thank you for this, and sorry to be a bother!

Yeah, I would actually advise against creating instances of `SceneReference` class in runtime. As I said it's main purpose is to serialize scene assets in the inspector.

The [`Scene` struct](https://docs.unity3d.com/ScriptReference/SceneManagement.Scene.html) is probably the best way to go for what you want to do.

No bothering at all, happy to help 🙂
