### ISSUE TITLE
QOL - Built in Package Manager support

### ISSUE THREAD

**Issue by xoorath** [JohannesMP/unity-scene-reference#9]
As a quality of life enhancement, it would be amazing if we could include this package using the built in package manager.

![image](https://user-images.githubusercontent.com/769014/107340841-11f53d00-6a73-11eb-929a-2b3507e376de.png)

Of course if I try to add the project from git url, I get this error:

> Cannot perform upm operation: Unable to add package [https://github.com/starikcetin/unity-scene-reference.git]:
>   [https://github.com/starikcetin/unity-scene-reference.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository. [NotFound]
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
>

**Comment by starikcetin** [comment]
Use a release tag:

```
https://github.com/starikcetin/unity-scene-reference.git#1.1.1
```

or the `upm` branch:

```
https://github.com/starikcetin/unity-scene-reference.git#upm
```

**Comment by xoorath** [comment]
Thanks @starikcetin !
